const normalize = (name: string) => name.trim().toLowerCase();

export const CARNATIC_RAGAS = [
  'Athana',
  'Naata',
  'Gowla',
  'Aarabhi',
  'Varali',
  'Sree',
  'Todi',
  'Umabharanam',
  'Kanthamani',
  'Kalyani',
  'Kambhoji',
  'Bhairavi',
  'Sankarabharanam',
  'Kharaharapriya',
  'Hamsadhwani',
  'Bahudari',
  'Sree Ranjani',
  'Nalinakanthi',
  'Saveri',
  'Mukhari',
  'Asaaveri',
  'Amrita Varshini',
  'Amrita Vaahini',
  'Anandabhairavi',
  'Kannada Gowla',
  'Kanada',
  'Kadanakutuhalam',
  'Khamas',
  'Chakravakam',
  'Dhanyasi',
  'Mayamalavagowla',
  'Bilahari',
  'Brindavanasaranga',
  'Reethigowla',
  'Vasantha',
  'Hindola',
  'Sahana',
  'Kalanidhi',
  'Shanmukhapriya',
  'Begada',
  'Sindhubhairavi',
  'Kaapi',
  'Yamuna Kalyani',
  'Abheri',
  'Abhogi',
  'Aandhali',
  'Aahiri',
  'Eesamanohari',
  'KannadaGoula',
  'Kamalamanohari',
  'Karnataka Suddhasaveri',
  'Kalavathi',
  'Yagapriya',
  'KalyanaVasantham',
  'Kanakangi',
  'Udayaravichandrika',
  'Surati',
  'Kannada',
  'Kapi Narayani',
  'Kamavardhini',
  'Kiranavali',
  'Keeravani',
  'Kuntalavarali',
  'Kurinji',
  'Kunjari',
  'Kedaram',
  'Kedaragowla',
  'Kaikavasi',
  'Kokiladhwani',
  'KokilaPriya',
  'KokilaVarali',
  'Kolahalam',
  'Gamanasrama',
  'Gavambhodhi',
  'Ganamurthi',
  'Gayakapriya',
  'Gowrimanohari',
  'Garudadhwani',
  'Gambheeravani',
  'Gaanavaridhi',
  'Gundakriya',
  'Goudamallaru',
  'Gowri',
  'Gowlipanti',
  'Ghanta',
  'Ghurjari',
  'ChalaNata',
  'Charukesi',
  'Chintamani',
  'Chitrambari',
  'Chittaranjani',
  'Chenchukambhoji',
  'Chayatarangini',
  'Chayanaata',
  'Jaganmohini',
  'Janaranjani',
  'Jenjuti',
  'Jayantasree',
  'Jayantasena',
  'Jayamonohari',
  'Jayanarayani',
  'Jalarnavam',
  'Jujaahuli',
  'Jyothiswarupini',
  'Jhalavarali',
  'Mohana',
  'Saranga',
  'Darbar',
  'Divyamani',
  'Dwijavanthi',
  'Dundubhi',
  'Devakriya',
  'Devamanohari',
  'Devagandhari',
  'Devamritavarshini',
  'Dhavalambari',
  'Dharmavati',
  'Dhatuvardhani',
  'Dheera Shankarabharanam',
  'Navaneetam',
  'Natakapriya',
  'Navarasakannada',
  'Nabhomani',
  'Natabhairavi',
  'Dhenuka',
  'Bhushavali',
  'Bhavapriya',
  'Bhinna Shadjamam',
  'Nalinikanti',
  'Nagagandhari',
  'Nagasvaravali',
  'Naganandini',
  'Nata',
  'Natakurunji',
  'Nada Nama Kriya',
  'Nada Varangini',
  'Nama Narayani',
  'Nayaki',
  'Yadukula Kambhoji',
  'Pharaju',
  'Brindavana Saranga',
  'Phalamanjari',
  'Purvi Kalyani',
  'Purna Shadjamam',
  'Purnalalitha',
  'Purnachandrika',
  'Prathapavarali',
  'Pavani',
  'Behag',
  'Bhouli',
  'Bhairavam',
  'Mohanakalyani',
  'Mecha Kalyani',
  'Malavasree',
  'Margahindola',
  'Maruvadhanyasi',
  'Mararanjani',
  'Malahari',
  'Malayamarutham',
  'Chandrajyoti',
  'Saama',
  'Swarabhushani',
  'Swaravali',
  'Sarasangi',
  'Saraswathi Manohari',
  'Saraswathi',
  'Lalitha',
  'Valaji',
  'Lathangi',
  'Reetigowla',
  'Ranjani',
  'PurviKalyani',
  'Raghupriya',
  'Rasali',
  'Neelambari',
  'Rasikapriya',
  'Ramamanohari',
  'Ratnangi',
  'Manohari',
  'Bindumalini',
  'Bangala',
  'Neetimathi',
  'Nasikabhushini',
  'Manirangu',
  'Aandolika',
  'Madhyamavathi',
  'Suddha Saveri',
  'Natakuranji',
  'Harikambhoji',
  'Saramathi',
] as const;

const CARNATIC_SET = new Set(CARNATIC_RAGAS.map(normalize));

export const isCarnaticRaga = (name: string) => CARNATIC_SET.has(normalize(name));
