const normalize = (name: string) => name.trim().toLowerCase();

export const CARNATIC_RAGAS = [
  'Udayaravichandrika',
  'Athana',
  'Naata',
  'Gowla',
  'Aarabhi',
  'Varali',
  'Sree',
  'Todi',
  'Kalyani',
  'Kambhoji',
  'Bhairavi',
  'Sankarabharanam',
  'Kharaharapriya',
  'Hamsadhwani',
  'Bahudari',
  'Sree Ranjani',
  'Nalinakanthi',
  'Saveri',
  'Mukhari',
  'Asaaveri',
  'Amrita Varshini',
  'Amrita Vaahini',
  'Anandabhairavi',
  'Kannada Gowla',
  'Kanada',
  'Khamas',
  'Chakravakam',
  'Dhanyasi',
  'Natakuranji',
  'Mayamalavagowla',
  'Bilahari',
  'Brindavanasaranga',
  'Reethigowla',
  'Vasantha',
  'Hindola',
  'Sahana',
  'Shanmukhapriya',
  'Surati',
  'Begada',
  'Sindhubhairavi',
  'Kaapi',
  'Yamuna Kalyani',
  'Abheri',
  'Abhogi',
  'Aandolika',
  'Aandhali',
  'Aahiri',
  'Eesamanohari',
  'Kannada',
  'KannadaGoula',
  'Kamalamanohari',
  'Karnataka Suddhasaveri',
  'Kalavathi',
  'Yagapriya',
  'KalyanaVasantham',
  'Kanakangi',
  'Umabharanam',
  'Kadanakutuhalam',
  'kalanidhi',
  'Kanthamani',
  'Kapi Narayani',
  'Kamavardhini',
  'Kiranavali',
  'Keeravani',
  'Kuntalavarali',
  'Kurinji',
  'Kunjari',
  'Kedaram',
  'Kedaragowla',
  'Kaikavasi',
  'Kokiladhwani',
  'KokilaPriya',
  'KokilaVarali',
  'Kolahalam',
  'Gamanasrama',
  'Gavambhodhi',
  'Ganamurthi',
  'Gayakapriya',
  'Gowrimanohari',
  'Garudadhwani',
  'Gambheeravani',
  'Gaanavaridhi',
  'Gundakriya',
  'Goudamallaru',
  'Gowri',
  'Gowlipanti',
  'Ghanta',
  'Ghurjari',
  'ChalaNata',
  'Chandrajyoti',
  'Charukesi',
  'Chintamani',
  'Chitrambari',
  'Chittaranjani',
  'Chenchukambhoji',
  'Chayatarangini',
  'Chayanaata',
  'Jaganmohini',
  'Janaranjani',
  'Jenjuti',
  'Jayantasree',
  'Jayantasena',
  'Jayamonohari',
  'Jayanarayani',
  'Jalarnavam',
  'Jujaahuli',
  'Jyothiswarupini',
  'Jhalavarali',
  'Mohana',
  'Saranga',
  'Darbar',
  'Divyamani',
  'Dwijavanthi',
  'Dundubhi',
  'Devakriya',
  'Devamanohari',
  'Devagandhari',
  'Devamritavarshini',
  'Dhavalambari',
  'Dharmavati',
  'Dhatuvardhani',
  'Dheera Shankarabharanam',
  'Dhenuka',
  'Natabhairavi',
  'Nabhomani',
  'Navaneetam',
  'Navarasakannada',
  'Natakapriya',
  'Nalinikanti',
  'Nagagandhari',
  'Nagasvaravali',
  'Naganandini',
  'Nata',
  'Natakurunji',
  'Nada Nama Kriya',
  'Nada Varangini',
  'Nama Narayani',
  'Nayaki',
] as const;

const CARNATIC_SET = new Set(CARNATIC_RAGAS.map(normalize));

export const isCarnaticRaga = (name: string) => CARNATIC_SET.has(normalize(name));
