const normalize = (name: string) => name.trim().toLowerCase();

export const CARNATIC_RAGAS = [
  'Aahiri',
  'Aandhali',
  'Aandolika',
  'Aarabhi',
  'Abheri',
  'Abhogi',
  'Amrita Vaahini',
  'Amrita Varshini',
  'Anandabhairavi',
  'Asaaveri',
  'Athana',
  'Bahudari',
  'Begada',
  'Behag',
  'Bhairavam',
  'Bhairavi',
  'Bhavapriya',
  'Bhinna Shadjamam',
  'Bhouli',
  'Bhushavali',
  'Bilahari',
  'Brindavana Saranga',
  'Brindavanasaranga',
  'Chakravakam',
  'ChalaNata',
  'Chandrajyoti',
  'Charukesi',
  'Chayanaata',
  'Chayatarangini',
  'Chenchukambhoji',
  'Chintamani',
  'Chitrambari',
  'Chittaranjani',
  'Darbar',
  'Devagandhari',
  'Devakriya',
  'Devamanohari',
  'Devamritavarshini',
  'Dhanyasi',
  'Dharmavati',
  'Dhatuvardhani',
  'Dhavalambari',
  'Dheera Shankarabharanam',
  'Dhenuka',
  'Divyamani',
  'Dundubhi',
  'Dwijavanthi',
  'Eesamanohari',
  'Gaanavaridhi',
  'Gamanasrama',
  'Gambheeravani',
  'Ganamurthi',
  'Garudadhwani',
  'Gavambhodhi',
  'Gayakapriya',
  'Ghanta',
  'Ghurjari',
  'Goudamallaru',
  'Gowla',
  'Gowlipanti',
  'Gowri',
  'Gowrimanohari',
  'Gundakriya',
  'Hamsadhwani',
  'Hindola',
  'Jaganmohini',
  'Jalarnavam',
  'Janaranjani',
  'Jayamonohari',
  'Jayanarayani',
  'Jayantasena',
  'Jayantasree',
  'Jenjuti',
  'Jhalavarali',
  'Jujaahuli',
  'Jyothiswarupini',
  'Kaapi',
  'Kadanakutuhalam',
  'Kaikavasi',
  'kalanidhi',
  'Kalavathi',
  'KalyanaVasantham',
  'Kalyani',
  'Kamalamanohari',
  'Kamavardhini',
  'Kambhoji',
  'Kanada',
  'Kanakangi',
  'Kannada',
  'Kannada Gowla',
  'KannadaGoula',
  'Kanthamani',
  'Kapi Narayani',
  'Karnataka Suddhasaveri',
  'Kedaragowla',
  'Kedaram',
  'Keeravani',
  'Khamas',
  'Kharaharapriya',
  'Kiranavali',
  'Kokiladhwani',
  'KokilaPriya',
  'KokilaVarali',
  'Kolahalam',
  'Kunjari',
  'Kuntalavarali',
  'Kurinji',
  'Malahari',
  'Malavasree',
  'Malayamarutham',
  'Mararanjani',
  'Margahindola',
  'Maruvadhanyasi',
  'Mayamalavagowla',
  'Mecha Kalyani',
  'Mohana',
  'Mohanakalyani',
  'Mukhari',
  'Naata',
  'Nabhomani',
  'Nada Nama Kriya',
  'Nada Varangini',
  'Nagagandhari',
  'Naganandini',
  'Nagasvaravali',
  'Nalinakanthi',
  'Nalinikanti',
  'Nama Narayani',
  'Nata',
  'Natabhairavi',
  'Natakapriya',
  'Natakuranji',
  'Natakurunji',
  'Navaneetam',
  'Navarasakannada',
  'Nayaki',
  'Pavani',
  'Phalamanjari',
  'Pharaju',
  'Prathapavarali',
  'Purna Shadjamam',
  'Purnachandrika',
  'Purnalalitha',
  'Purvi Kalyani',
  'Reethigowla',
  'Sahana',
  'Sankarabharanam',
  'Saranga',
  'Saveri',
  'Shanmukhapriya',
  'Sindhubhairavi',
  'Sree',
  'Sree Ranjani',
  'Surati',
  'Todi',
  'Udayaravichandrika',
  'Umabharanam',
  'Varali',
  'Vasantha',
  'Yadukula Kambhoji',
  'Yagapriya',
  'Yamuna Kalyani',
] as const;

const CARNATIC_SET = new Set(CARNATIC_RAGAS.map(normalize));

export const isCarnaticRaga = (name: string) => CARNATIC_SET.has(normalize(name));
