const normalize = (name: string) => name.trim().toLowerCase();

export const HINDUSTANI_RAGAS = [
  'Aadi',
  'Abhogi',
  'Abhogi Kanada',
  'Achob',
  'Adana',
  'Adbhut Kalyan',
  'Ahir Bhairav',
  'Alhaiya Bilaval',
  'Amrith Kalyan',
  'Amritvarshini',
  'Asa',
  'Asavari',
  'Audav',
  'Bageshri',
  'Bairagi',
  'Barwa',
  'Basant',
  'Beehad',
  'Bhairav',
  'Bhairavi (Hindustani)',
  'Bhatiyar',
  'Bhimpalasi',
  'Bhinna Shadja',
  'Bhoop',
  'Bhupal Todi',
  'Bibhas',
  'Bihag',
  'Bilaskhani Todi',
  'Bilaval',
  'Brindavani Sarang',
  'Chandrakauns',
  'Chhayanat',
  'Darbar',
  'Darbari Kanada',
  'Desh',
  'Desi',
  'Dhanashree',
  'Dhani',
  'Durga',
  'Gaud Malhar',
  'Gaud Sarang',
  'Gauri',
  'Gorakh Kalyan',
  'Gujjari',
  'Gunakri',
  'Gurjari',
  'Hameer',
  'Hindol',
  'Jaijaivanti',
  'Jaunpuri',
  'Jhinjhoti',
  'Jog',
  'Jogiya',
  'Kafi',
  'Kalavati',
  'Kanada (family of ragas)',
  'Kedar',
  'Khamaj',
  'Kirwani',
  'Komal Rishabh Asavari',
  'Lalit',
  'Madhuwanti',
  'Malgunji',
  'Malhar',
  'Malkauns',
  'Marva',
  'Megh',
  'Megh Malhar',
  'Multani',
  'Nat Bhairav',
  'Patdeep',
  'Pilu',
  'Puriya',
  'Puriya Dhanashree',
  'Purvi',
  'Rageshree',
  'Ramkali',
  'Sahana',
  'Shankara',
  'Shivaranjani',
  'Shree',
  'Sohni',
  'Sorath',
  'Suhi',
  'Test',
  'Tilak Kamod',
  'Todi',
  'Yaman',
  'Yaman Kalyan',
  'Zeelaf'
] as const;

const HINDUSTANI_SET = new Set(HINDUSTANI_RAGAS.map(normalize));

export const isHindustaniRaga = (name: string) => HINDUSTANI_SET.has(normalize(name));
