const normalize = (name: string) => name.trim().toLowerCase();

export const HINDUSTANI_RAGAS = [
  'Aadi',
  'Aarabi',
  'Abhogi',
  'Abhogi Kanada',
  'Achob',
  'Adaanaa',
  'Adana',
  'Adbhut Kalyan',
  'Ahir Bhairav',
  'Alhaiya Bilaval',
  'Amrith Kalyan',
  'Amritvarshini',
  'Asa',
  'Asavari',
  'Asavari (Shuddh Rishabh Asavari)',
  'Audav',
  'Bageshri',
  'Bahaar',
  'Bairagi',
  'Barwa',
  'Basant',
  'Beehad',
  'Bhairav',
  'Bhairavi',
  'Bhatiyar',
  'Bhimpalasi',
  'Bhinna Shadja',
  'Bhoop',
  'Bhupal Todi',
  'Bibhas',
  'Bihag',
  'Bilaawal',
  'Bilaskhani Todi',
  'Brindavani Sarang',
  'Chandrakaant',
  'Chandrakauns',
  'Chhayanat',
  'Darbar',
  'Darbari Kanada',
  'Desh',
  'Deshkaar',
  'Desi',
  'Devgiri Bilawal',
  'Dhanashree',
  'Dhani',
  'Durga',
  'Gaud Malhar',
  'Gaud Sarang',
  'Gauri',
  'Gorakh Kalyan',
  'Gujjari',
  'Gunakri',
  'Gurjari',
  'Hameer',
  'Hem Kalyan',
  'Hindol',
  'Jaijaivanti',
  'Jait Kalyan',
  'Jaunpuri',
  'Jhinjhoti',
  'Jog',
  'Jogiya',
  'Kaafi',
  'Kaalingadaa',
  'Kaamod',
  'Kalavati',
  'Kanada',
  'Kedar',
  'Khamaj',
  'Kirwani',
  'Komal Rishabh Asavari',
  'Lalit',
  'Madhuwanti',
  'Malgunji',
  'Malhar',
  'Malkauns',
  'Marwa',
  'Megh (raga)',
  'Megh Malhar',
  'Multani',
  'Nat Bhairav',
  'Patdeep',
  'Pilu',
  'Puriya',
  'Puriya Dhanashree',
  'Purvi',
  'Rageshree',
  'Ramkali',
  'Sahana',
  'Shankara',
  'Shivaranjani',
  'Shree',
  'Shuddha Kalyan',
  'Shyam Kalyan',
  'Sohni',
  'Sorath (raga)',
  'Suhi (raga)',
  'Sundarkauns',
  'Test',
  'Tilak Kamod',
  'Tilang',
  'Todi',
  'Vibhas',
  'Yaman',
  'Yaman Kalyan',
  'Zeelaf'
] as const;

const HINDUSTANI_SET = new Set(HINDUSTANI_RAGAS.map(normalize));

export const isHindustaniRaga = (name: string) => HINDUSTANI_SET.has(normalize(name));
