const normalize = (name: string) => name.trim().toLowerCase();

export const HINDUSTANI_RAGAS = [
  'Aadi',
  'Aarabi',
  'Abheeri',
  'Abhogi',
  'Abhogi Kanada',
  'Achob',
  'Adaanaa',
  'Adana',
  'Adbhut Kalyan',
  'Ahir Bhairav',
  'Alhaiya Bilaval',
  'Amrith Kalyan',
  'Amritvarshini',
  'Asa',
  'Asavari',
  'Asavari (Shuddh Rishabh Asavari)',
  'Asawari',
  'Asawari (Bhairavi)',
  'Asawari (Variant)',
  'Audav',
  'Bageshri',
  'Bahaar',
  'Bahaduri Todi',
  'Bahar',
  'Bairagi bhairav',
  'Barva',
  'Barwa',
  'Basant',
  'Basant (Poorvi)',
  'Basant Mukhari',
  'Beehad',
  'Behagra',
  'Bhairav',
  'Bhairavi',
  'Bhatiyar',
  'Bhimpalasi',
  'Bhinna Shadja',
  'Bhoop',
  'Bhoopal Todi',
  'Bhoopali',
  'Bhupal Todi',
  'Bibhas',
  'Bibhas (Poorvi)',
  'Bihag',
  'Bilaawal',
  'Bilaskhani Todi',
  'Brindabani Sarang',
  'Brindavani Sarang',
  'Budhans',
  'Chanchal ki Malhar',
  'Chandra Kant',
  'Chandrakaant',
  'Chandrakauns',
  'Charju ki Malhar',
  'Chhayanat',
  'Chhayanat',
  'Darbar',
  'Darbari Kanada',
  'Deepak',
  'Deosakh',
  'Des',
  'Des Gaund',
  'Desh',
  'Deshkaar',
  'Desi',
  'Dev Ranjini',
  'Devagandhari',
  'Devgiri',
  'Devgiri Bilawal',
  'Dhanashree',
  'Dhanashri',
  'Dhanashri (Bhairavi)',
  'Dhani',
  'Dhani',
  'Dhulya Malhar',
  'Durbari Kanada',
  'Durga',
  'Durga (Khamaj Ang)',
  'Gandhari',
  'Gara',
  'Gaud',
  'Gaud Malhar',
  'Gaud Sarang',
  'Gauri',
  'Gauri (Poorvi)',
  'Gopika Basant',
  'Gorakh Kalyan',
  'Gujjari',
  'Gujri Todi',
  'Gunakri',
  'Gunkali',
  'Gurjari',
  'Hameer',
  'Hans Kankani',
  'Hans Narayan',
  'Hejaz',
  'Hem Kalyan',
  'Hindol',
  'Huseini Kanhra',
  'Jaijaivanti',
  'Jait Kalyan',
  'Jangula',
  'Jangula (Bhairavi)',
  'Jaunpuri',
  'Jeelaf',
  'Jejewanti',
  'Jet Kalyan',
  'Jeteshri',
  'Jhinjhoti',
  'Jog',
  'Jogiya',
  'Jonpuri',
  'Kaafi',
  'Kaalingadaa',
  'Kaamod',
  'Kafi',
  'Kalavati',
  'Kamod',
  'Kanada',
  'Kaukab',
  'Kedar',
  'Khamaj',
  'Khambavati',
  'Khut',
  'Khut Todi',
  'Kirwani',
  'Komal Bageshri',
  'Komal Desi',
  'Komal Rishabh Asavari',
  'Kosi Kanhra',
  'Kumari',
  'Lachchhasakh',
  'Lalit',
  'Lankadahan Sarang',
  'Madhmadh Sarang',
  'Madhuwanti',
  'Malgunji',
  'Malhar',
  'Malkauns',
  'Malsari',
  'Malvi',
  'Mand',
  'Manohar',
  'Marwa',
  'Megh (raga)',
  'Megh Malhar',
  'Mirabai ki Malhar',
  'Miyan ki Malhar',
  'Miyan ki Sarang',
  'Motaki',
  'Mudrakee',
  'Mulla',
  'Multani',
  'Mundareek Kanada',
  'Nag Soravali',
  'Naiki Kanhra',
  'Narayani',
  'Nat Bhairav',
  'Nat Bilawal',
  'Neelambari',
  'Nut Malhar',
  'Odava Devgiri',
  'Pahadi',
  'Paraj',
  'Pardeepaki',
  'Pat Manjari',
  'Patdeep',
  'Patmanjari',
  'Peelu',
  'Pilu',
  'Plasi',
  'Pooriya Dhanashri',
  'Poorvi',
  'Pratab Varali',
  'Puriya',
  'Puriya Dhanashree',
  'Purvi',
  'Rageshree',
  'Rageshri',
  'Raj Pulandika',
  'Ramdasi Malhar',
  'Ramkali',
  'Reva',
  'Roop Manjari',
  'Sahana',
  'Sarparda',
  'Sarvari',
  'Savani Kalyan',
  'Savant',
  'Saveri',
  'Sawant Sarang',
  'Shahana',
  'Shankara',
  'Shivaranjani',
  'Shree',
  'Shri',
  'Shri Ranjini',
  'Shri Tank',
  'Shuddh Bilawal',
  'Shuddh Malhar',
  'Shuddha Kalyan',
  'Shuddha Sarang',
  'Shukal Bilawal',
  'Shyam Kalyan',
  'Sindh Bhairavi',
  'Sindhavi',
  'Sindhura',
  'Sohni',
  'Sorath',
  'Sorath (raga)',
  'Sughrai',
  'Suha',
  'Suha Sughrai',
  'Suhi (raga)',
  'Sundarkauns',
  'Surdasi Malhar',
  'Test',
  'Tilak',
  'Tilak Kamod',
  'Tilang',
  'Todi',
  'Triveni',
  'Uttar Ghanakali',
  'Vibhas',
  'Yaman',
  'Yaman (raga2)',
  'Yaman Bilawal',
  'Yaman Kalyan',
  'Yaman(raga1_)',
  'Zeelaf'
] as const;

const HINDUSTANI_SET = new Set(HINDUSTANI_RAGAS.map(normalize));

export const isHindustaniRaga = (name: string) => HINDUSTANI_SET.has(normalize(name));
