export type MelakartaRaga = {
  number: number;
  name: string;
  chakra: string;
};

export const MELAKARTA_RAGAS: MelakartaRaga[] = [
  { number: 1, name: 'Kanakangi', chakra: 'Indu' },
  { number: 2, name: 'Ratnangi', chakra: 'Indu' },
  { number: 3, name: 'Ganamurti', chakra: 'Indu' },
  { number: 4, name: 'Vanaspati', chakra: 'Indu' },
  { number: 5, name: 'Manavati', chakra: 'Indu' },
  { number: 6, name: 'Tanarupi', chakra: 'Indu' },
  { number: 7, name: 'Senavati', chakra: 'Netra' },
  { number: 8, name: 'Hanumatodi', chakra: 'Netra' },
  { number: 9, name: 'Dhenuka', chakra: 'Netra' },
  { number: 10, name: 'Natakapriya', chakra: 'Netra' },
  { number: 11, name: 'Kokilapriya', chakra: 'Netra' },
  { number: 12, name: 'Rupavati', chakra: 'Netra' },
  { number: 13, name: 'Gayakapriya', chakra: 'Agni' },
  { number: 14, name: 'Vakulabharanam', chakra: 'Agni' },
  { number: 15, name: 'Mayamalavagowla', chakra: 'Agni' },
  { number: 16, name: 'Chakravakam', chakra: 'Agni' },
  { number: 17, name: 'Suryakantam', chakra: 'Agni' },
  { number: 18, name: 'Hatakambari', chakra: 'Agni' },
  { number: 19, name: 'Jhankaradhwani', chakra: 'Veda' },
  { number: 20, name: 'Natabhairavi', chakra: 'Veda' },
  { number: 21, name: 'Keeravani', chakra: 'Veda' },
  { number: 22, name: 'Kharaharapriya', chakra: 'Veda' },
  { number: 23, name: 'Gourimanohari', chakra: 'Veda' },
  { number: 24, name: 'Varunapriya', chakra: 'Veda' },
  { number: 25, name: 'Mararanjani', chakra: 'Bana' },
  { number: 26, name: 'Charukesi', chakra: 'Bana' },
  { number: 27, name: 'Sarasangi', chakra: 'Bana' },
  { number: 28, name: 'Harikambhoji', chakra: 'Bana' },
  { number: 29, name: 'Dheerasankarabharanam', chakra: 'Bana' },
  { number: 30, name: 'Naganandini', chakra: 'Bana' },
  { number: 31, name: 'Yagapriya', chakra: 'Rutu' },
  { number: 32, name: 'Ragavardhini', chakra: 'Rutu' },
  { number: 33, name: 'Gangeyabhushani', chakra: 'Rutu' },
  { number: 34, name: 'Vagadheeswari', chakra: 'Rutu' },
  { number: 35, name: 'Shulini', chakra: 'Rutu' },
  { number: 36, name: 'Chalanata', chakra: 'Rutu' },
  { number: 37, name: 'Salagam', chakra: 'Rishi' },
  { number: 38, name: 'Jalarnavam', chakra: 'Rishi' },
  { number: 39, name: 'Jhalavarali', chakra: 'Rishi' },
  { number: 40, name: 'Navaneetam', chakra: 'Rishi' },
  { number: 41, name: 'Pavani', chakra: 'Rishi' },
  { number: 42, name: 'Raghupriya', chakra: 'Rishi' },
  { number: 43, name: 'Gavambhodi', chakra: 'Vasu' },
  { number: 44, name: 'Bhavapriya', chakra: 'Vasu' },
  { number: 45, name: 'Shubhapantuvarali', chakra: 'Vasu' },
  { number: 46, name: 'Shadvidamargini', chakra: 'Vasu' },
  { number: 47, name: 'Suvarnangi', chakra: 'Vasu' },
  { number: 48, name: 'Divyamani', chakra: 'Vasu' },
  { number: 49, name: 'Dhavalambari', chakra: 'Brahma' },
  { number: 50, name: 'Namanarayani', chakra: 'Brahma' },
  { number: 51, name: 'Kamavardani', chakra: 'Brahma' },
  { number: 52, name: 'Ramapriya', chakra: 'Brahma' },
  { number: 53, name: 'Gamanashrama', chakra: 'Brahma' },
  { number: 54, name: 'Vishwambari', chakra: 'Brahma' },
  { number: 55, name: 'Shamalangi', chakra: 'Disi' },
  { number: 56, name: 'Shanmukhapriya', chakra: 'Disi' },
  { number: 57, name: 'Simhendramadhyamam', chakra: 'Disi' },
  { number: 58, name: 'Hemavati', chakra: 'Disi' },
  { number: 59, name: 'Dharmavati', chakra: 'Disi' },
  { number: 60, name: 'Neetimati', chakra: 'Disi' },
  { number: 61, name: 'Kantamani', chakra: 'Rudra' },
  { number: 62, name: 'Rishabhapriya', chakra: 'Rudra' },
  { number: 63, name: 'Latangi', chakra: 'Rudra' },
  { number: 64, name: 'Vachaspati', chakra: 'Rudra' },
  { number: 65, name: 'Mechakalyani', chakra: 'Rudra' },
  { number: 66, name: 'Chitrambari', chakra: 'Rudra' },
  { number: 67, name: 'Sucharitra', chakra: 'Aditya' },
  { number: 68, name: 'Jyotiswarupini', chakra: 'Aditya' },
  { number: 69, name: 'Dhatuvardani', chakra: 'Aditya' },
  { number: 70, name: 'Nasikabhushani', chakra: 'Aditya' },
  { number: 71, name: 'Kosalam', chakra: 'Aditya' },
  { number: 72, name: 'Rasikapriya', chakra: 'Aditya' },
];

export const MELAKARTA_BY_NUMBER = new Map(
  MELAKARTA_RAGAS.map((entry) => [entry.number, entry])
);
