// Mapping for Carnatic swara abbreviations to full names.
export const SWARA_MAP: Record<string, string> = {
  'S.R': 'Suddha Rishabham',
  'C.R': 'Chatusruti Rishabham',
  'SHA.R': 'Shatsruti Rishabham',
  'S.G': 'Sadharana Gandharam',
  'SA.G': 'Sadharana Gandharam',
  'A.G': 'Antara Gandharam',
  'SU.G': 'Suddha Gandharam',
  'S.M': 'Suddha Madhyamam',
  'P.M': 'Prati Madhyamam',
  'S.D': 'Suddha Daivatam',
  'C.D': 'Chatusruti Daivatam',
  'SHA.D': 'Shatsruti Daivatam',
  'K.N': 'Kaisiki Nishadam',
  'KK.N': 'Kakali Nishadam',
  'SU.N': 'Suddha Nishadam',
  P: 'Panchamam',
  S: 'Shadjam',
};

export const MELAKARTHA_MAP: Record<number, string> = {
  1: 'Kanakangi',
  2: 'Ratnangi',
  3: 'Ganamurti',
  4: 'Vanaspati',
  5: 'Manavati',
  6: 'Tanarupi',
  7: 'Senavati',
  8: 'Hanumatodi',
  9: 'Dhenuka',
  10: 'Natakapriya',
  11: 'Kokilapriya',
  12: 'Rupavati',
  13: 'Gayakapriya',
  14: 'Vakulabharanam',
  15: 'Mayamalavagowla',
  16: 'Chakravakam',
  17: 'Suryakantam',
  18: 'Hatakambari',
  19: 'Jhankaradhwani',
  20: 'Natabhairavi',
  21: 'Keeravani',
  22: 'Kharaharapriya',
  23: 'Gourimanohari',
  24: 'Varunapriya',
  25: 'Mararanjani',
  26: 'Charukesi',
  27: 'Sarasangi',
  28: 'Harikambhoji',
  29: 'Dheerasankarabharanam',
  30: 'Naganandini',
  31: 'Yagapriya',
  32: 'Ragavardhini',
  33: 'Gangeyabhushani',
  34: 'Vagadheeswari',
  35: 'Shulini',
  36: 'Chalanata',
  37: 'Salagam',
  38: 'Jalarnavam',
  39: 'Jhalavarali',
  40: 'Navaneetam',
  41: 'Pavani',
  42: 'Raghupriya',
  43: 'Gavambhodhi',
  44: 'Bhavapriya',
  45: 'Shubhapanthuvarali',
  46: 'Shadvidhamargini',
  47: 'Suvarnangi',
  48: 'Divyamani',
  49: 'Dhavalambari',
  50: 'Namanarayani',
  51: 'Kamavardhini',
  52: 'Ramapriya',
  53: 'Gamanashrama',
  54: 'Vishwambhari',
  55: 'Shyamala',
  56: 'Shanmukhapriya',
  57: 'Simhendramadhyamam',
  58: 'Hemavati',
  59: 'Dharmavati',
  60: 'Neetimati',
  61: 'Kantamani',
  62: 'Rishabhapriya',
  63: 'Latangi',
  64: 'Vachaspati',
  65: 'Mechakalyani',
  66: 'Chitrambari',
  67: 'Sucharitra',
  68: 'Jyoti Swarupini',
  69: 'Dhatuvardhani',
  70: 'Nasikabhushani',
  71: 'Kosalam',
  72: 'Rasikapriya',
};

export const expandSwaraValue = (value?: string | null) => {
  if (!value) return value;
  return value
    .split(',')
    .map((part) => {
      const trimmed = part.trim();
      const full = SWARA_MAP[trimmed.toUpperCase()];
      return full ?? trimmed;
    })
    .join(', ');
};
